accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'accounts'
urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

agents/urls.py
from django.urls import path
from . import views

app_name = 'agents'
urlpatterns = [
    path('', views.agent_list_view, name='agent-list'),
    path('<slug:slug>/', views.agent_details_view, name='agent-detail'),
    path('<slug:slug>/edit/', views.agent_edit_view, name='agent-edit'),
]

top_property/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('properties/', include('properties.urls', namespace='properties')),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=20, unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    password1 = forms.CharField(
        label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg form-control-a'}))
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput(attrs={'class': 'form-control form-control-lg form-control-a'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name',
                  'username', 'password1', 'password2')


class UpdateForm(forms.ModelForm):
    email = forms.EmailField(label='Email', widget=forms.EmailInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    first_name = forms.CharField(label='First Name', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    last_name = forms.CharField(label='Last Name', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))
    username = forms.CharField(label='Username', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email', 'first_name', 'last_name',
                  'username',)

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.shortcuts import render, redirect
from .forms import SignUpForm
from .tokens import account_activation_token

User = get_user_model()


def login_view(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            message = messages.success(
                request, ('You have logged in successfully'))
            return redirect('home')
    return render(request, 'accounts/login.html')


def signup_view(request):
    form = SignUpForm()

    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            subject = f'Activate Your {current_site} account'
            message = render_to_string('accounts/account-activation.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user)
            })
            email = EmailMessage(
                f'{current_site} - Password Reset',
                message,
                settings.EMAIL_HOST_USER,
                [user.email]
            )
            email.fail_silently = False
            email.send()
            messages.success(
                request, ('Signup Successful, Please confirm your email to complete registration'))
            return redirect('accounts:login')

    context = {
        'form': form
    }
    return render(request, 'accounts/signup.html', context)


def signout(request):
    logout(request)
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return redirect('accounts:login')
    else:
        return HttpResponse('Email activation failed.')

templates/accounts/account-activation.html
{% autoescape off %} 
Hi {{ user.username }}, 
Please click on the link below to confirm your registration: 
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: EstateAgency - v4.3.0
  * Template URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>
<body>
  {% block content %}{% endblock content %}
  {% include '../includes/scripts.html' %}  
</body>
</html>

templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title %}Login{% endblock title %}
{% block content %}
<div class="container col-4">
  <div class="title-box-d py-4">
    <h3 class="title-d">Login</h3>
  </div>
  <div class="form">
    <form class="form-a" method="post">
      {% csrf_token %}
      <div class="row">
        <div class="col-md-12 mb-2">
          <div class="form-group">
            <label class="pb-2" for="Type">Email</label>
            <input type="email" name="email" class="form-control form-control-lg form-control-a">
          </div>
          <div class="form-group">
            <label class="pb-2" for="Type">Password</label>
            <input type="password" name="password" class="form-control form-control-lg form-control-a">
          </div>
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-b">Login</button>
        </div>
      </div>
    </form>
    <div class="col-12">
      <p class="mt-3 col-6">Don't have an account? <a href="{% url 'accounts:signup' %}">Signup</a></p>
      <p class="mt-3 col-6"><a href="{% url 'password_reset' %}">Forgot your password?</a></p>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends '../base.html' %}
{% block title %}Password Reset Form{% endblock title %}
{% block content %}
<div class="intro-single">
  <div class="container">
    <h2 class="mb-3">Password reset complete</h2>
    <p>Your password has been set. You may go ahead and log in now.</p>
    <a href="{% url 'accounts:login' %}">Log in</a>
  </div>
</div>
{% endblock content %}

templates/accounts/password_reset_confirm.html
{% extends '../base.html' %}
{% block title %}Password Reset Form{% endblock title %}
{% block content %}
<div class="intro-single">
  <div class="container">
    <p>Reset password</p>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-b">Reset Password</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/accounts/password_reset_done.html
{% extends '../base.html' %}
{% block title %}Password Reset Form{% endblock title %}
{% block content %}
<div class="intro-single">
  <div class="container">
    <h2 class="mb-3">Password reset send</h2>
    <p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You
      should
      receive them shortly.</p>
    
    <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam
      folder.</p>
  </div>
</div>
{% endblock content %}

templates/accounts/password_reset_form.html
{% extends '../base.html' %}
{% block title %}Password Reset Form{% endblock title %}
{% block content %}
<div class="intro-single">
  <div class="container">
    <h3>Password reset</h3>
    <p>Enter your email address below for instructions on how to reset your password</p>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <!-- <input type="submit" value="submit" name="send email" class="btn btn-b"> -->
      <button type="submit" class="btn btn-b">Reset Password</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/accounts/signup.html
{% extends 'accounts/base.html' %}
{% block title %}Signup{% endblock title %}
{% block content %}
<div class="container col-4">
  <div class="title-box-d py-4">
    <h3 class="title-d">Signup</h3>
  </div>
  <div class="form">
    <form class="form-a" action="" method="post">
      <div class="row">
        <div class="col-md-12 mb-2">
          <!-- <div class="form-group">
            <label class="pb-2" for="Type">Keyword</label>
            <input type="text" class="form-control form-control-lg form-control-a" placeholder="Keyword">
          </div> -->
          {% csrf_token %}
          {{ form.as_p }}
        </div>
        <div class="col-md-12">
          <button type="submit" class="btn btn-b">Signup</button>
        </div>
      </div>
    </form>
    <p class="mt-3">Already have an account? <a href="{% url 'accounts:signup' %}">Login</a></p>
  </div>
</div>
{% endblock content %}