agents/urls.py
from django.urls import path
from . import views

app_name = 'agents'
urlpatterns = [
    path('', views.agent_list_view, name='agent-list'),
    path('<slug:slug>/', views.agent_details_view, name='agent-detail'),
    path('<slug:slug>/edit/', views.agent_edit_view, name='agent-edit'),
]

properties/urls.py
from unicodedata import name
from django.urls import path
from . import views

app_name = 'properties'
urlpatterns = [
    path('', views.property_list_view, name='property-list'),
    path('create/', views.property_create_view, name='property-create'),
    path('<slug:slug>/', views.property_detail_view, name='property-detail'),
    path('<slug:slug>/update/', views.property_update_view, name='property-update'),
    path('<slug:slug>/delete/', views.property_delete_view, name='property-delete'),
]

top_property/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('general.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('properties/', include('properties.urls', namespace='properties')),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset_form.html'),
         name='password_reset'),

    path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),

    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

properties/models.py
from tabnanny import verbose
from django.db import models
from agents.models import Agent
from autoslug import AutoSlugField


class Property(models.Model):
    class Meta:
        verbose_name_plural = 'Properties'

    class PropertyType(models.TextChoices):
        AGRICULTURAL = 'agricultural', 'Agricultural'
        COMMERCIAL = 'commercial', 'Commercial'
        INDUSTRIAL = 'industrial', 'Industrial'
        RESIDENTIAL = 'residential', 'Residential'
        SPECIAL_USE = 'special use', 'Special Use'

    class Status(models.TextChoices):
        RENT = 'rent', 'Rent'
        SALE = 'sale', 'Sale'

    agent = models.ForeignKey(
        Agent, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=200, unique=True)
    city = models.CharField(max_length=10)
    country = models.CharField(max_length=10)
    zipcode = models.CharField(max_length=10)
    description = models.TextField()
    price = models.CharField(max_length=20)
    beds = models.IntegerField()
    baths = models.IntegerField()
    garage = models.IntegerField()
    area = models.IntegerField()
    property_picture = models.ImageField(upload_to='images/property_images')
    video = models.FileField(
        upload_to='videos/property_videos/', null=True, blank=True)
    property_type = models.CharField(
        'PropertyType', max_length=30, choices=PropertyType.choices, default=PropertyType.RESIDENTIAL)
    status = models.CharField('Status', max_length=10,
                              choices=Status.choices, default=Status.SALE)
    slug = AutoSlugField(unique=True, always_update=True,
                         populate_from='address')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    @property
    def video_url(self):
        try:
            video = self.video.url
        except:
            video = ''
        return video

    @property
    def image_url(self):
        try:
            image = self.property_picture.url
        except:
            image = ''
        return image

    def __str__(self):
        return f'{self.agent} - {self.address}'


class PropertyImage(models.Model):
    class Meta:
        verbose_name_plural = 'Property Images'

    property = models.ForeignKey(
        'Property', on_delete=models.CASCADE, null=True, related_name='property_images')
    image = models.ImageField(upload_to='images/property-images/')

    def image_url(self):
        try:
            image = self.image.url
        except:
            image = ''
        return image

    def __str__(self):
        return f'Image for {self.property}'


class Amenity(models.Model):
    class Meta:
        verbose_name_plural = 'Amenities'

    property = models.ForeignKey(
        'Property', on_delete=models.CASCADE, null=True, related_name='property_amenities')
    amenity = models.CharField(max_length=500)

    def __str__(self):
        return f'{self.amenity}'

properties/forms.py
from django import forms
from .models import Amenity, Property, PropertyImage


class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = ('address', 'city', 'country', 'zipcode', 'beds', 'baths',
                  'garage', 'area', 'description', 'price', 'property_picture', 'video', 'property_type', 'status',)
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'city': forms.TextInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'country': forms.TextInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'beds': forms.NumberInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'baths': forms.NumberInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'garage': forms.NumberInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'area': forms.NumberInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'description': forms.Textarea(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'price': forms.TextInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'property_picture': forms.FileInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'video': forms.FileInput(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'property_type': forms.Select(attrs={'class': 'form-control form-control-lg form-control-a'}),
            'status': forms.Select(attrs={'class': 'form-control form-control-lg form-control-a'})
        }


class AmenityForm(forms.ModelForm):
    amenity = forms.CharField(max_length=500, label='Amenities (Seperated by commas)', widget=forms.TextInput(
        attrs={'class': 'form-control form-control-lg form-control-a'}))

    class Meta:
        model = Amenity
        fields = ('amenity',)


class PropertyImageForm(forms.ModelForm):
    class Meta:
        model = PropertyImage
        fields = ('image',)
        labels = {
            'image': 'Images'
        }
        widgets = {
            'image': forms.FileInput(attrs={'class': 'form-control form-control-lg form-control-a', 'multiple': True})
        }

properties/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from .forms import AmenityForm, PropertyForm, PropertyImageForm
from .models import Amenity, Property, PropertyImage
from agents.models import Agent, SocialAccount


def property_list_view(request):
    properties = Property.objects.all()

    context = {
        'properties': properties,
    }
    return render(request, 'properties/property-list.html', context)


@login_required(login_url='accounts:login')
def property_create_view(request):
    agent = Agent.objects.get(user=request.user)
    amenity_form = AmenityForm
    property_form = PropertyForm
    property_image_form = PropertyImageForm

    if request.method == 'POST':
        amenity_form = AmenityForm(request.POST)
        property_form = PropertyForm(request.POST, request.FILES)
        property_image_form = PropertyImageForm(request.POST, request.FILES)

        if amenity_form.is_valid() and property_form.is_valid() and property_image_form.is_valid():
            property = property_form.save(commit=False)
            property.agent = agent
            property.save()

            amenities = amenity_form.cleaned_data['amenity'].split(',')

            for amenity in amenities:
                Amenity.objects.create(property=property, amenity=amenity)
            for image in request.FILES.getlist('image'):
                PropertyImage.objects.create(property=property, image=image)

            return redirect('properties:property-list')

    context = {
        'amenity_form': amenity_form,
        'property_form': property_form,
        'property_image_form': property_image_form,
    }
    return render(request, 'properties/property-create.html', context)


def property_detail_view(request, slug):
    property = Property.objects.get(slug=slug)
    amenities = Amenity.objects.filter(property=property) or None
    property_images = PropertyImage.objects.filter(property=property)
    social_accounts = SocialAccount.objects.get(agent=property.agent) or None

    context = {
        'property': property,
        'amenities': amenities,
        'property_images': property_images,
        'social_accounts': social_accounts,
    }
    return render(request, 'properties/property-detail.html', context)


@login_required(login_url='accounts:login')
def property_update_view(request, slug):
    property = Property.objects.get(slug=slug)
    property_form = PropertyForm(instance=property)

    if request.user != property.agent.user:
        return HttpResponseForbidden(f'<p>Not allowed. You are not authenticated as {property.agent.user}</p><a href="/agents/">Go back to agent list</a>')

    if request.method == 'POST':
        property_form = PropertyForm(
            request.POST, request.FILES, instance=property)

        if property_form.is_valid():
            new_property = property_form.save()

            return redirect('properties:property-detail', new_property.slug)

    context = {
        'property_form': property_form,
    }

    return render(request, 'properties/property-update.html', context)


@login_required(login_url='accounts:login')
def property_delete_view(request, slug):
    property = Property.objects.get(slug=slug)
    if request.user != property.agent.user:
        return HttpResponseForbidden(f'<p>Not allowed. You are not authenticated as {property.agent.user}</p><a href="/agents/">Go back to agent list</a>')

    if request.method == 'POST':
        property.delete()
        return redirect('properties:property-list')

    return render(request, 'properties/property-delete.html', {'property': property})

templates/properties/property-create.html
{% extends '../base.html' %}
{% block title %}Add Property{% endblock title %}
{% block content %}
<main id="main">
  <section class="intro-single">
    <div class="container col-sm-8 col-md-4">
      <div class="title-box-d py-4 mx-auto">
        <h3 class="title-d">Edit Agent Profile</h3>
      </div>
      <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ property_form.as_p }}
          {{ property_image_form.as_p }}
          {{ amenity_form.as_p }}
          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Add Property</button>
          </div>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

templates/properties/property-delete.html
{% extends '../base.html' %}
{% block title %}Delete Property{% endblock title %}
{% block content %}
<main id="main">
  <section class="intro-single">
    <div class="container col-sm-8 col-md-6">
      <div class="title-box-d py-4 mx-auto">
        <h3 class="title-d">Are you sure you want to delete {{ property.address }}?</h3>
      </div>
      <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <a href="{% url 'properties:property-detail' property.slug %}" class="btn btn-b mr-5">Go back</a>
              <button style="background-color: red; color: white;" type="submit" class="btn btn-b">Delete Property</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock content %}

templates/properties/property-detail.html
{% extends '../base.html' %}
{% load static %}
{% block title %}{{ property.address }}{% endblock title %}
{% block content %}
<main id="main">

  <!-- ======= Intro Single ======= -->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">{{ property.address }}</h1>
            <span class="color-text-a">Chicago, IL 606543</span>
            {% if request.user == property.agent.user %}
            <div class="mt-3 col-md-12">
              <a style="padding: 12px;" href="{% url 'properties:property-update' property.slug %}" type="submit" class="mr-3 btn btn-b">Update Property</a>
              {% if request.user.is_superuser %}
                <a style="padding: 12px; background-color: red; color: white;" href="{% url 'properties:property-delete' property.slug %}" type="submit" class="btn btn-b">Delete Property</a>
              {% endif %}
            </div>
            {% endif %}
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'home' %}">Home</a>
              </li>
              <li class="breadcrumb-item">
                <a href="{% url 'properties:property-list' %}">Properties</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                {{ property.address }}
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section><!-- End Intro Single-->

  <!-- ======= Property Single ======= -->
  <section class="property-single nav-arrow-b">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div id="property-single-carousel" class="swiper-container">
            <div class="swiper-wrapper">
              {% for property_image in property_images %}
              <div class="carousel-item-b swiper-slide">
                <img src="{{ property_image.image_url }}" alt="">
              </div>
              {% endfor %}
            </div>
          </div>
          <div class="property-single-carousel-pagination carousel-pagination"></div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-12">

          <div class="row justify-content-between">
            <div class="col-md-5 col-lg-4">
              <div class="property-price d-flex justify-content-center foo">
                <div class="card-header-c d-flex">
                  <div class="card-box-ico">
                    <span class="bi bi-cash">$</span>
                  </div>
                  <div class="card-title-c align-self-center">
                    <h5 class="title-c">{{ property.price }}</h5>
                  </div>
                </div>
              </div>
              <div class="property-summary">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="title-box-d section-t4">
                      <h3 class="title-d">Quick Summary</h3>
                    </div>
                  </div>
                </div>
                <div class="summary-list">
                  <ul class="list">
                    <li class="d-flex justify-content-between">
                      <strong>Property ID:</strong>
                      <span>{{ property.id }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Location:</strong>
                      <span>{{ property.city }}, {{ property.country }} {{ property.zipcode }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Property Type:</strong>
                      <span>{{ property.property_type }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Status:</strong>
                      <span>{{ property.status }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Area:</strong>
                      <span>{{ property.area }}m
                        <sup>2</sup>
                      </span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Beds:</strong>
                      <span>{{ property.beds }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Baths:</strong>
                      <span>{{ property.baths }}</span>
                    </li>
                    <li class="d-flex justify-content-between">
                      <strong>Garage:</strong>
                      <span>{{ property.garage }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-7 col-lg-7 section-md-t3">
              <div class="row">
                <div class="col-sm-12">
                  <div class="title-box-d">
                    <h3 class="title-d">Property Description</h3>
                  </div>
                </div>
              </div>
              <div class="property-description">
                <p class="description color-text-a">
                  {{ property.description }}
                </p>
              </div>
              <div class="row section-t3">
                <div class="col-sm-12">
                  <div class="title-box-d">
                    <h3 class="title-d">Amenities</h3>
                  </div>
                </div>
              </div>
              <div class="amenities-list color-text-a">
                <ul class="list-a no-margin">
                  {% for amenity in amenities %}
                  <li>{{ amenity }}</li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-10 offset-md-1">
          <ul class="nav nav-pills-a nav-pills mb-3 section-t3" id="pills-tab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="pills-video-tab" data-bs-toggle="pill" href="#pills-video" role="tab"
                aria-controls="pills-video" aria-selected="true">Video</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pills-plans-tab" data-bs-toggle="pill" href="#pills-plans" role="tab"
                aria-controls="pills-plans" aria-selected="false">Floor Plans</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="pills-map-tab" data-bs-toggle="pill" href="#pills-map" role="tab"
                aria-controls="pills-map" aria-selected="false">Ubication</a>
            </li>
          </ul>
          <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
              <iframe src="https://player.vimeo.com/video/73221098" width="100%" height="460" frameborder="0"
                webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
            </div>
            <div class="tab-pane fade" id="pills-plans" role="tabpanel" aria-labelledby="pills-plans-tab">
              <img src="{% static 'img/plan2.jpg' %}" alt="" class="img-fluid">
            </div>
            <div class="tab-pane fade" id="pills-map" role="tabpanel" aria-labelledby="pills-map-tab">
              <iframe
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.1422937950147!2d-73.98731968482413!3d40.75889497932681!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25855c6480299%3A0x55194ec5a1ae072e!2sTimes+Square!5e0!3m2!1ses-419!2sve!4v1510329142834"
                width="100%" height="460" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="row section-t3">
            <div class="col-sm-12">
              <div class="title-box-d">
                <h3 class="title-d">Contact Agent</h3>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6 col-lg-4">
              <img src="{{ property.agent.image_url }}" alt="" class="img-fluid">
            </div>
            <div class="col-md-6 col-lg-4">
              <div class="property-agent">
                <h4 class="title-agent">
                  {{ property.agent.user.first_name}}
                  {{ property.agent.user.last_name }}
                </h4>
                <p class="color-text-a">
                  {{ property.agent.bio }}
                </p>
                <ul class="list-unstyled">
                  <li class="d-flex justify-content-between">
                    <strong>Phone:</strong>
                    <span class="color-text-a">{{ property.agent.phone_number }}</span>
                  </li>
                  <li class="d-flex justify-content-between">
                    <strong>Email:</strong>
                    <span class="color-text-a">{{ property.agent.user.email }}</span>
                  </li>
                </ul>
                <div class="socials-a">
                  <ul class="list-inline">
                    <li class="list-inline-item">
                      <a href="{{ social_accounts.facebook }}">
                        <i class="bi bi-facebook" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="{{ social_accounts.twitter }}">
                        <i class="bi bi-twitter" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="{{ social_accounts.instagram }}">
                        <i class="bi bi-instagram" aria-hidden="true"></i>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="{{ social_accounts.linkedin }}">
                        <i class="bi bi-linkedin" aria-hidden="true"></i>
                      </a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div class="col-md-12 col-lg-4">
              <div class="property-contact">
                <form class="form-a">
                  <div class="row">
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <input type="text" class="form-control form-control-lg form-control-a" id="inputName"
                          placeholder="Name *" required>
                      </div>
                    </div>
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <input type="email" class="form-control form-control-lg form-control-a" id="inputEmail1"
                          placeholder="Email *" required>
                      </div>
                    </div>
                    <div class="col-md-12 mb-1">
                      <div class="form-group">
                        <textarea id="textMessage" class="form-control" placeholder="Comment *" name="message" cols="45"
                          rows="8" required></textarea>
                      </div>
                    </div>
                    <div class="col-md-12 mt-3">
                      <button type="submit" class="btn btn-a">Send Message</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- End Property Single-->

</main><!-- End #main -->
{% endblock content %}

templates/properties/property-list.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Properties{% endblock title %}
{% block content %}
<main id="main">

  <!-- ======= Intro Single ======= -->
  <section class="intro-single">
    <div class="container">
      <div class="row">
        <div class="col-md-12 col-lg-8">
          <div class="title-single-box">
            <h1 class="title-single">Available Properties</h1>
            <!-- <span class="color-text-a">Grid Properties</span> -->
          </div>
        </div>
        <div class="col-md-12 col-lg-4">
          <nav aria-label="breadcrumb" class="breadcrumb-box d-flex justify-content-lg-end">
            <ol class="breadcrumb">
              <li class="breadcrumb-item">
                <a href="{% url 'home' %}">Home</a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">
                Properties Grid
              </li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </section><!-- End Intro Single-->

  <!-- ======= Property Grid ======= -->
  <section class="property-grid grid">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <div class="grid-option">
            <form>
              <select class="custom-select">
                <option selected>All</option>
                <option value="1">New to Old</option>
                <option value="2">For Rent</option>
                <option value="3">For Sale</option>
              </select>
            </form>
          </div>
        </div>
        {% for property in properties %}
        <div class="col-md-4">
          <div class="card-box-a card-shadow">
            <div class="img-box-a">
              <img src="{{ property.image_url }}" alt="" class="img-a img-fluid">
            </div>
            <div class="card-overlay">
              <div class="card-overlay-a-content">
                <div class="card-header-a">
                  <h2 class="card-title-a">
                    <a href="{% url 'properties:property-detail' property.slug %}">{{ property.address }}</a>
                  </h2>
                </div>
                <div class="card-body-a">
                  <div class="price-box d-flex">
                    <span class="price-a">{{ property.status }} | $ {{ property.price }}</span>
                  </div>
                  <a href="{{ property.slug }}" class="link-a">Click here to view
                    <span class="bi bi-chevron-right"></span>
                  </a>
                </div>
                <div class="card-footer-a">
                  <ul class="card-info d-flex justify-content-around">
                    <li>
                      <h4 class="card-info-title">Area</h4>
                      <span>{{ property.area }}m
                        <sup>2</sup>
                      </span>
                    </li>
                    <li>
                      <h4 class="card-info-title">Beds</h4>
                      <span>{{ property.beds }}</span>
                    </li>
                    <li>
                      <h4 class="card-info-title">Baths</h4>
                      <span>{{ property.baths }}</span>
                    </li>
                    <li>
                      <h4 class="card-info-title">Garages</h4>
                      <span>{{ property.garage }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <!-- pagination -->
      <div class="row">
        <div class="col-sm-12">
          <nav class="pagination-a">
            <ul class="pagination justify-content-end">
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">
                  <span class="bi bi-chevron-left"></span>
                </a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">1</a>
              </li>
              <li class="page-item active">
                <a class="page-link" href="#">2</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="#">3</a>
              </li>
              <li class="page-item next">
                <a class="page-link" href="#">
                  <span class="bi bi-chevron-right"></span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </section><!-- End Property Grid Single-->

</main><!-- End #main -->
{% endblock content %}

templates/properties/property-update.html
{% extends '../base.html' %}
{% block title %}Update Property{% endblock title %}
{% block content %}
<main id="main">
  <section class="intro-single">
    <div class="container col-sm-8 col-md-4">
      <div class="title-box-d py-4 mx-auto">
        <h3 class="title-d">Edit Property Details</h3>
      </div>
      <div class="row">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {{ property_form.as_p }}
          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Update Property</button>
          </div>
        </form>
      </div>
    </div>
  </section>
</main>
{% endblock content %}